ALTER TABLE APP_USER DROP CONSTRAINT FK_APP_USER_ROLE_ID;
ALTER TABLE STUDY_SET DROP CONSTRAINT FK_STUDY_SET_OWNER_ID;
ALTER TABLE FLASHCARD DROP CONSTRAINT FK_FLASHCARD_CATEGORY_ID;
ALTER TABLE STUDY_SET_CARD DROP CONSTRAINT FK_STUDY_SET_CARD_STUDY_SET_ID;
ALTER TABLE STUDY_SET_CARD DROP CONSTRAINT FK_STUDY_SET_CARD_FLASHCARD_ID;

DROP TABLE USER_ROLE;
DROP TABLE APP_USER;
DROP TABLE STUDY_SET;
DROP TABLE STUDY_SET_CARD;
DROP TABLE FLASHCARD;
DROP TABLE CATEGORY;

CREATE TABLE USER_ROLE (
    ROLE_ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE APP_USER (
    USER_ID NUMBER(10) PRIMARY KEY,
    USERNAME VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    ROLE_ID NUMBER(10)
);

ALTER TABLE APP_USER ADD CONSTRAINT FK_APP_USER_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES USER_ROLE(ROLE_ID);

CREATE TABLE STUDY_SET (
    STUDY_SET_ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(100) UNIQUE NOT NULL,
    OWNER_ID NUMBER(10)
);

ALTER TABLE STUDY_SET ADD CONSTRAINT FK_STUDY_SET_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES APP_USER(USER_ID) ON DELETE CASCADE;

CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE FLASHCARD (
    FLASHCARD_ID NUMBER(10) PRIMARY KEY,
    QUESTION VARCHAR2(100) UNIQUE NOT NULL,
    ANSWER VARCHAR2(100) NOT NULL,
    CATEGORY_ID NUMBER(10)
);

ALTER TABLE FLASHCARD ADD CONSTRAINT FK_FLASHCARD_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);

CREATE TABLE STUDY_SET_CARD (
    STUDY_SET_ID NUMBER(10),
    FLASHCARD_ID NUMBER(10)    
);

ALTER TABLE STUDY_SET_CARD ADD CONSTRAINT FK_STUDY_SET_CARD_STUDY_SET_ID FOREIGN KEY (STUDY_SET_ID) REFERENCES STUDY_SET(STUDY_SET_ID);
ALTER TABLE STUDY_SET_CARD ADD CONSTRAINT FK_STUDY_SET_CARD_FLASHCARD_ID FOREIGN KEY (FLASHCARD_ID) REFERENCES FLASHCARD(FLASHCARD_ID);

CREATE TABLE DUAL(
    DUMMY NUMBER(38)
);

INSERT INTO DUAL VALUES(0);

SELECT ABS(-100) FROM DUAL;

SELECT (CALL ABSOLUTE_VALUE(-100)) FROM DUAL;
