CREATE OR REPLACE PROCEDURE CREATE_APP_USER(USERNAME VARCHAR2, PASSWORD VARCHAR2, FIRST_NAME VARCHAR2, LAST_NAME VARCHAR2, ROLE_ID NUMBER)
IS
BEGIN
INSERT INTO APP_USER VALUES (INCREMENT_BY_THREE.NEXTVAL, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, ROLE_ID);
END;

CREATE OR REPLACE PROCEDURE CREATE_USER_ROLE(NAME VARCHAR2)
IS
BEGIN
INSERT INTO USER_ROLE VALUES (INCREMENT_BY_THREE.NEXTVAL, NAME);
END;

CREATE OR REPLACE PROCEDURE CREATE_STUDY_SET(NAME VARCHAR2, OWNER_ID NUMBER)
IS
BEGIN
INSERT INTO STUDY_SET VALUES (INCREMENT_BY_THREE.NEXTVAL,NAME, OWNER_ID);
END;

CREATE OR REPLACE PROCEDURE CREATE_FLASHCARD(QUESTION VARCHAR2, ANSWER VARCHAR2,CATEGORY_ID NUMBER)
IS
BEGIN
INSERT INTO FLASHCARD VALUES (INCREMENT_BY_THREE.NEXTVAL, QUESTION, ANSWER, CATEGORY_ID);
END;

CREATE OR REPLACE PROCEDURE CREATE_CATEGORY(NAME VARCHAR2)
IS
BEGIN
INSERT INTO CATEGORY VALUES (INCREMENT_BY_THREE.NEXTVAL, NAME);
END;

CREATE OR REPLACE PROCEDURE ABS_VAL (nin IN NUMBER)
IS
BEGIN
 SELECT ABS(nin) INTO nin FROM DUAL;
END;

CALL ABS_VAL (-100, null);

CREATE OR REPLACE FUNCTION ABSOLUTE_VALUE (nin NUMBER) RETURN NUMBER
IS
BEGIN
return ABS(nin);
END;
