SELECT USERNAME, NAME, QUESTION, ANSWER FROM (SELECT USERNAME, USER_ID FROM APP_USER WHERE USER_ID = 5),
(SELECT OWNER_ID AS C, NAME, QUESTION, ANSWER FROM
(SELECT OWNER_ID, FLASHCARD_ID AS A FROM STUDY_SET_CARD, STUDY_SET WHERE STUDY_SET.STUDY_SET_ID = STUDY_SET_CARD.STUDY_SET_ID),
(SELECT FLASHCARD_ID AS B, NAME, QUESTION, ANSWER FROM FLASHCARD, CATEGORY WHERE FLASHCARD.CATEGORY_ID = CATEGORY.CATEGORY_ID)
WHERE A = B) WHERE USER_ID = C;